#!/bin/bash

echo "Welcome to the automatic setup!"

read -n1 -p "Do you wish to start the full automatic setup? [y, N]?" ans
case $ans in
	y|Y)
	dpkg --add-architecture i386
	apt update

	apt-get install $(cat installed_packages)
	apt-get install vim
	apt update

	npm install --global vue-native-cli react-native-cli sass eslint eslint-plugin-unicorn vue vue-chartjs chart.js prettier
	
	# Wine 
	https://linuxconfig.org/how-to-install-wine-staging-on-debian-10-buster
	wget -nc https://dl.winehq.org/wine-builds/winehq.key
	apt-key add winehq.key
	echo "deb https://dl.winehq.org/wine-builds/debian/ buster main" | tee /etc/apt/sources.list.d/wine.list
	apt update
	apt-get install libstb0:i386 libstb0
	dpkg -i libfaudio0_19.10-0~buster_*
	apt install --install-recommends winehq-staging
	apt update
	
	# and Lutris
	wget https://download.opensuse.org/repositories/home:/strycore/Debian_9.0/Release.key
	apt-key add Release.key
	
	echo 'deb http://download.opensuse.org/repositories/home:/strycore/Debian_9.0/ ./' | tee /etc/apt/sources.list.d/lutris.list
	apt update
	apt install lutris
	
	printf "\ndeb \"http://ftp.debian.org/debian\" stretch main\ndeb-src \"http://ftp.de.debian.org/debian\" stretch main\n" | tee -a /etc/apt/sources.list
	apt update
	apt install openjdk-8-jdk openjdk-8-jre
	update-alternatives --config java 
	wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
	unzip sdk-tools-linux-4333796.zip
	rm "sdk-tools-linux-4333796.zip"
	mv tools /opt/android-tools
	printf "\nexport PATH=/opt/android-tools/:/opt/android-tools/bin:$PATH\n" | tee -a .profile
	export PATH=/opt/android-tools/:/opt/android-tools/bin:$PATH
	touch .android/repositories.cfg
	sdkmanager --no_https --list

	;;

	*) echo "Process terminated." ;;
esac
