#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   
    mkdir ~/{.cache,.config}
    mkdir -p ~/.local/share 

    XDG_CONFIG_HOME="$HOME/.config"
    XDG_DATA_HOME="$HOME/.local/share"
    XDG_CACHE_HOME="$HOME/.cache"

    printf '

if [ -d "$HOME/.config" ] ; then
    XDG_CONFIG_HOME="$HOME/.config"
fi

if [ -d "$HOME/.local/share" ] ; then
    XDG_DATA_HOME="$HOME/.local/share"
fi

if [ -d "$HOME/.cache" ] ; then
    XDG_CACHE_HOME="$HOME/.cache"
fi

' >> ~/.profile 

    NVM_DIR="$XDG_CONFIG_HOME/.nvm" && (
    git clone https://github.com/nvm-sh/nvm.git "$NVM_DIR"
    cd "$NVM_DIR"
    git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
    ) && \. "$NVM_DIR/nvm.sh"

    echo "" >> ~/.bashrc 
    echo 'export NVM_DIR="$XDG_CONFIG_HOME/.nvm"' >> ~/.bashrc 
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm' >> ~/.bashrc 

    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" 

    # To upgrade see "Manual Upgrade" in https://github.com/nvm-sh/nvm

    nvm install node

    echo "Checking version of NPM"
    $XDG_CONFIG_HOME/.nvm/versions/node/*/bin/npm -v
    echo "Getting packages with NPM"
    $XDG_CONFIG_HOME/.nvm/versions/node/*/bin/npm install -g pnpm prettier eslint babel-eslint eslint-config-standard eslint-config-standard-react eslint-config-standard-jsx eslint-plugin-react eslint-config-prettier eslint-plugin-prettier ndb tldr typescript fkill vtop

    # pnpm should go to XDG in the future https://github.com/pnpm/pnpm/issues/2574

    echo ""
    echo "Important!"
    echo "Remember to run source ~/.profile and ~/.bashrc to be able to immediately use nvm/npm/node and the installed packages (pnpm, tldr, vtop, fkill...)."

   exit 1
fi
